[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
coinflip = "FLipUd6iHP9KTncLCt6Jo9bXXaz4yV4SuDpZdgRqVRHe"
mock_vrf = "8DeY7XokDSxSC5nJjwuoYW8Ajjo36UH9XXpu247tcJWf"

[programs.devnet]
coinflip = "FLipUd6iHP9KTncLCt6Jo9bXXaz4yV4SuDpZdgRqVRHe"

[programs.mainnet]
coinflip = "FLipUd6iHP9KTncLCt6Jo9bXXaz4yV4SuDpZdgRqVRHe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [".", "mock-vrf"]

[scripts]
test = "mkdir -p target/deploy && cp mock-vrf/keypair.json target/deploy/mock_vrf-keypair.json && npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
